Repository lowRISC/sonata-system, pull requests merged in 2024-11, with the labels that each got.

#316 Update PMOD and USB timing constraints
  data/synth_timing.xdc
Labels: 1.0

#328 Make PLIC test fail when interrupt not fired
  sw/cheri/tests/plic_tests.hh
Labels: 1.0

#336 Fixup RS485 after pinmux changes
  rtl/system/sonata_system.sv
  sw/cheri/checks/rs485_check.cc
  sw/cheri/checks/rs485_spam_check.cc
Labels: bug, 1.0

#341 Connect arduino shield pin 9 to correct PWM channel
  data/top_config.toml
  doc/ip/pinmux/README.md
  rtl/system/pinmux.sv
Labels: bug, 1.0

#343 Update pinmux mapping diagram to match `top_config.toml`
  doc/ip/pinmux/pin_mappings.dot
  doc/ip/pinmux/pin_mappings.svg
Labels: post-1.0
